---
baseurl: "https://www.jareddickson.com/"
languageCode: "en-us"
metaDataFormat: "yaml"
theme: "casper"
title: "Jared Dickson"
params:
  author: "Jared Dickson"
  authorlocation: "Grand Rapids, MI"
  authorwebsite: "https://www.jareddickson.com"
  cover: "images/cover.jpg"
  description: "Ghost Developer, Brewmaster, Musician"
  githubName: "kraihn"
  googleAnalyticsUserID: "UA-41892654-1"
  hideHUGOSupport: false
  twitterName: "kraihn"
---
